runtime: php74

vpc_access_connector:
  name: projects/cs-portal-api-development/locations/asia-northeast1/connectors/connector01
  egress_setting: all-traffic

runtime_config:
  document_root: ./public

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico

  - url: /robots.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: .*
    script: auto

includes:
- .gcp/env.yaml

env_variables:
  APP_NAME: "CS Portal API"

  LOG_FILE_PATH: /tmp/logs/laravel.log

  SESSION_DRIVER: array

  VIEW_COMPILED_PATH: /tmp

  CACHE_FILE_PATH: /tmp/framework/cache/data

  DOCTRINE_CACHE: file
