version: '3'

services:
  api-nginx:
    image: nginx:1.19-alpine
    depends_on:
      - api-php
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  api-php:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./docker/wiremock/stubs:/home/wiremock
