version: '3'

services:
  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - php
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
