# CircleCI configuration

version: 2.1

commands:
  file_exists:
    description: "Checks whether a file exists"
    parameters:
      file:
        type: string
    steps:
      - run:
          name: Checks whether "<< parameters.file >>" exists
          command: |
            if [ -e << parameters.file >> ]; then
              echo "File exists."
              exit 0
            else
              echo "File not exists."
              exit 1
            fi

  azure_zip_deploy:
    description: "Azure ZIP Deploy"
    parameters:
      app:
        type: string
      user:
        type: string
      password:
        type: string
      zip:
        type: string
    steps:
      - run:
          name: Deploy to Azure
          command: |
            mkdir deploy
            curl -s -X POST https://<< parameters.user >>:<< parameters.password >>@<< parameters.app >>.scm.azurewebsites.net/api/zipdeploy -T << parameters.zip >> -o ./deploy/result.html -w '%{http_code}' > ./deploy/http_code.txt
            if [ $(cat ./deploy/http_code.txt) -eq "200" ]; then
                echo "Deploy successful."
                exit 0
            else
                echo "Deploy failed."
                exit 1
            fi

      - store_artifacts:
          path: ./deploy

executors:
  build:
    docker:
      - image: circleci/php:7.3

  deployment:
    docker:
      - image: cimg/base:stable

jobs:
  build_development:
    working_directory: ~/development
    executor: build

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-dev-{{ checksum "composer.lock" }}
            - composer-

      - run:
          name: Composer install (with require-dev)
          command: composer install --dev -n --prefer-dist

      - save_cache:
          key: composer-dev-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Generate Doctrine Proxies
          command: php artisan doctrine:generate:proxies

      - run:
          name: Create .user.ini file
          command: cp .user.ini.development .user.ini

      - run:
          name: Create version file
          command: echo "${CIRCLE_SHA1}.${CIRCLE_BUILD_NUM}" | tee version.txt

      - run:
          name: ZIP archive
          command: >-
            zip -r app_development.zip
            app azure bootstrap config database public resources routes storage vendor artisan .user.ini README.md version.txt
            -x public/.htaccess

      - store_artifacts:
          path: ./app_development.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  build_production:
    working_directory: ~/production
    executor: build

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
            - composer-

      - run:
          name: Composer install
          command: composer install  -n --prefer-dist --optimize-autoloader

      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Generate Doctrine Proxies
          command: php artisan doctrine:generate:proxies

      - run:
          name: Create .user.ini file
          command: cp .user.ini.production .user.ini

      - run:
          name: Create version file
          command: echo "${CIRCLE_SHA1}.${CIRCLE_BUILD_NUM}" | tee version.txt

      - run:
          name: ZIP archive
          command: >-
            zip -r app.zip
            app azure bootstrap config database public resources routes storage vendor artisan .user.ini README.md version.txt
            -x public/.htaccess

      - store_artifacts:
          path: ./app.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/development
    executor: build

    steps:
      - attach_workspace:
          at: .

      - run:
          name: PHP Lint
          command: composer phplint

      - run:
          name: PHP CodeSniffer
          command: composer phpcs

      - run:
          name: PHPStan
          command: composer phpstan

      - run:
          name: PHPUnit
          command: composer test-unit

  deploy_to_dev:
    working_directory: ~/development
    executor: deployment
    steps:
      - attach_workspace:
          at: .

      - file_exists:
          file: app_development.zip

      - azure_zip_deploy:
          app: ssk-portal2018-api-win-dev
          user: $DEV_AAS_USER
          password: $DEV_AAS_PASSWORD
          zip: app_development.zip

  deploy_to_prod_release:
    working_directory: ~/production
    executor: deployment

    steps:
      - attach_workspace:
          at: .

      - file_exists:
          file: app.zip

      - azure_zip_deploy:
          app: ssk-portal2018-api-win-prod-release
          user: $PROD_RELEASE_AAS_USER
          password: $PROD_RELEASE_AAS_PASSWORD
          zip: app.zip

workflows:
  version: 2

  deploy_development:
    jobs:
      - build_development:
          filters:
            branches:
              ignore: master

      - test:
          requires:
            - build_development

      - deploy_approval:
          type: approval
          requires:
            - test

      - deploy_to_dev:
          requires:
            - deploy_approval

  deploy_production:
    jobs:
      - build_development:
          filters:
            branches:
              only: master

      - test:
          requires:
            - build_development

      - build_production:
          requires:
            - test

      - deploy_approval:
          type: approval
          requires:
            - build_production

      - deploy_to_prod_release:
          requires:
            - deploy_approval
