# CircleCI configuration

version: 2.1

# YAML記法を使った参照（CircleCIの設定ではない）
# https://circleci.com/docs/ja/2.0/writing-yaml/#%E3%82%A2%E3%83%B3%E3%82%AB%E3%83%BC%E3%81%A8%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%82%B9
references:

  # https://circleci.com/docs/ja/2.0/private-images/
  # https://m-p.backlog.jp/alias/file/7162903
  docker_hub_authentication: &docker_hub_authentication
    auth:
      username: $DOCKERHUB_ID
      password: $DOCKERHUB_ACCESS_TOKEN

  job_setup: &job_setup
    context: docker-hub-creds

commands:
  fix_composer_version:
    description: "Composerのバージョンを固定"
    steps:
      - run:
          name: Using Composer version 2
          command: sudo composer self-update --2

  file_exists:
    description: "Checks whether a file exists"
    parameters:
      file:
        type: string
    steps:
      - run:
          name: Checks whether "<< parameters.file >>" exists
          command: |
            if [ -e << parameters.file >> ]; then
              echo "File exists."
              exit 0
            else
              echo "File not exists."
              exit 1
            fi

orbs:
  azure-cli: circleci/azure-cli@1.2.0

executors:
  build:
    docker:
      - image: circleci/php:7.4
        <<: *docker_hub_authentication

  test:
    docker:
      - image: circleci/php:7.4
        <<: *docker_hub_authentication

        # 基本は.env.testingなどで設定する
        # 差分が大きくなるようなら専用の.envファイルを作成するなど
        environment:
          DB_HOST: "127.0.0.1"

      - image: circleci/mysql:5.7
        <<: *docker_hub_authentication
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: qwer4321
          TZ: "Asia/Tokyo"

jobs:
  build_development:
    working_directory: ~/development
    executor: build

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-dev-{{ checksum "composer.lock" }}
            - composer-

      - fix_composer_version

      - run:
          name: Composer install (with require-dev)
          command: composer install --dev -n --prefer-dist

      - save_cache:
          key: composer-dev-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Generate Doctrine Proxies
          command: php artisan doctrine:generate:proxies

      - run:
          name: Create PHP configuration file (for Azure)
          command: cp ./azure/ini/settings.ini-development ./azure/ini/settings.ini

      - run:
          name: Create version file
          command: echo "${CIRCLE_SHA1}.${CIRCLE_BUILD_NUM}" | tee version.txt

      - run:
          name: ZIP archive
          command: >-
            zip -r app_development.zip
            app azure bootstrap config database public resources routes storage vendor artisan README.md version.txt
            -x public/.htaccess

      - store_artifacts:
          path: ./app_development.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  build_production:
    working_directory: ~/production
    executor: build

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
            - composer-

      - fix_composer_version

      - run:
          name: Composer install
          command: composer install  -n --prefer-dist --optimize-autoloader

      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Generate Doctrine Proxies
          command: php artisan doctrine:generate:proxies

      - run:
          name: Create PHP configuration file (for Azure)
          command: cp ./azure/ini/settings.ini-production ./azure/ini/settings.ini

      - run:
          name: Create version file
          command: echo "${CIRCLE_SHA1}.${CIRCLE_BUILD_NUM}" | tee version.txt

      - run:
          name: ZIP archive
          command: >-
            zip -r app.zip
            app azure bootstrap config database public resources routes storage vendor artisan README.md version.txt
            -x public/.htaccess

      - store_artifacts:
          path: ./app.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/development
    executor: test

    steps:
      - run:
          name: Install PHP Extension
          command: sudo docker-php-ext-install pdo_mysql

      - attach_workspace:
          at: .

      - run:
          name: PHP Lint
          command: composer phplint

      - run:
          name: PHP CodeSniffer
          command: composer phpcs

      - run:
          name: PHPStan
          command: composer phpstan

      - run:
          name: PHPUnit
          command: composer test

  deploy_to_dev:
    working_directory: ~/development
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: .

      - file_exists:
          file: app_development.zip

      - azure-cli/login-with-user:
          alternate-tenant: true

      - run:
          name: Deploy
          command: >-
            az webapp deployment source config-zip \
              -g ssk-portal-win-dev \
              -n ssk-portal2018-api-win-dev \
              --src app_development.zip

  deploy_to_prod_release:
    working_directory: ~/production
    executor: azure-cli/azure-docker

    steps:
      - attach_workspace:
          at: .

      - file_exists:
          file: app.zip

      - azure-cli/login-with-user:
          alternate-tenant: true

      - run:
          name: Deploy
          command: >-
            az webapp deployment source config-zip \
              -g ssk-portal-win-prod \
              -n ssk-portal2018-api-win-prod \
              -s release \
              --src app.zip

  swap_prod_release_to_production:
    working_directory: ~/production
    executor: azure-cli/azure-docker

    steps:
      - azure-cli/login-with-user:
          alternate-tenant: true

      - run:
          name: Slot swap
          command: az webapp deployment slot swap -g ssk-portal-win-prod -n ssk-portal2018-api-win-prod --slot release --target-slot production


workflows:
  version: 2

  deploy_development:
    jobs:
      - build_development:
          <<: *job_setup
          filters:
            branches:
              ignore: master

      - test:
          <<: *job_setup
          requires:
            - build_development

      - deploy_approval:
          type: approval
          requires:
            - test

      - deploy_to_dev:
          <<: *job_setup
          requires:
            - deploy_approval

  deploy_production:
    jobs:
      - build_development:
          <<: *job_setup
          filters:
            branches:
              only: master

      - test:
          <<: *job_setup
          requires:
            - build_development

      - build_production:
          <<: *job_setup
          requires:
            - test

      - deploy_approval:
          type: approval
          requires:
            - build_production

      - deploy_to_prod_release:
          <<: *job_setup
          requires:
            - deploy_approval

      - swap_approval:
          type: approval
          requires:
            - deploy_to_prod_release

      - swap_prod_release_to_production:
          <<: *job_setup
          requires:
            - swap_approval
